server:
  port: 1121
spring:
  application:
    name: library-management-system
  datasource:
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}
    type: com.zaxxer.hikari.HikariDataSource
    url: ${datasource.url}
    maxLifetime: 1800000
    maximumPoolSize: 128
    minimumIdle: 10
    idleTimeout: 600000
    connectionTimeout: 5000
    connectionTestQuery: select 1
  redis:
    database: 1
    host: ${redis.host}
    password: ${redis.password}
    port: ${redis.port}
    timeout: 3000
    pool:
      max-idle: 8
      min-idle: 4
      max-active: 32
      max-wait: 3000
endpoints:
  shutdown:
    enabled: true
    sensitive: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.user}:${eureka.password}@${eureka.server}
    healthcheck:
      enabled: false
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

mybatis:
  mapperLocations: classpath:config/database/mapper/*.xml
  typeAliasesPackage: cn.tjrac.demo.vo

logging:
  level:
    cn.tjrac.demo.dao: debug
